### ISSUE TITLE
 ReferenceError: Can't find variable: require after update to newest version

### ISSUE THREAD

**Issue by nimloth05** [danfma/kodando#3]
I use kodando-rxjs for my project, and after updating from version 5.0.0-v5 to 5.3.0-v1.1 I got the following error executing my karma tests:

 ReferenceError: Can't find variable: require
[INFO]   at <PROJECT>/client/target/test-js/kodando-runtime.js:379

I'm not sure if the previous version of kodando was deployed with UMD as module system (kotline-js compiler setting) or if it was random that it worked previously on my project. At the time of writing, commonJS is set on the root of the pom.xml of kodando, is there a reason not to use UMD? From the explanation JetBrains gives, UMD sounds like good choice for a lib?

Honestly I'm not sure what further information you would need to guide me to a solution for my problem.

**Comment by danfma** [comment]
Hey man,

You are right. The previous package was defined as UMD and now its defined as COMMONJS and that was the cause of your problem.

I changed because I thought that nobody was using the library in this format. But let's do the following, I will change the format back to UMD as soon as I come back to my house (~2hours from now) and republish the library, then I tell you again in this issue.

Sorry about that and thanks for using it. I'll get the opportunity to put the missing operators  (sometimes I need more to work and probably you too)!

Are you using it with some library or purely? Just to know.

**Comment by danfma** [comment]
Probably I will spend more time to get to my home. I'll keep you informed.
